CREATE TABLE IF NOT EXISTS ausencias (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  ausente TEXT NOT NULL,
  guardia TEXT DEFAULT '',
  aula TEXT DEFAULT '',
  faena INTEGER NOT NULL DEFAULT 0,
  obs TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biblioteca_guardias (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  profesor TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(dia, hora)
);

CREATE TABLE IF NOT EXISTS historial (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  detail TEXT DEFAULT '',
  type TEXT DEFAULT 'other',
  actor TEXT DEFAULT 'Jefatura',
  ts TEXT NOT NULL,
  undo_state TEXT
);

CREATE TABLE IF NOT EXISTS tareas_profesorado (
  id TEXT PRIMARY KEY,
  profesor TEXT NOT NULL,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  dejada INTEGER NOT NULL DEFAULT 0,
  tarea TEXT DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS session_overrides (
  id TEXT PRIMARY KEY,
  profesor TEXT NOT NULL,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  materia TEXT DEFAULT '',
  grupo TEXT DEFAULT '',
  detalle TEXT DEFAULT '',
  aula TEXT DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
