CREATE TABLE IF NOT EXISTS ausencias (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  ausente TEXT NOT NULL,
  guardia TEXT DEFAULT '',
  aula TEXT DEFAULT '',
  faena INTEGER NOT NULL DEFAULT 0,
  obs TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biblioteca_guardias (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  profesor TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(dia, hora)
);

CREATE TABLE IF NOT EXISTS historial (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  detail TEXT DEFAULT '',
  type TEXT DEFAULT 'other',
  actor TEXT DEFAULT 'Jefatura',
  ts TEXT NOT NULL,
  undo_state TEXT
);

CREATE TABLE IF NOT EXISTS tareas_profesorado (
  id TEXT PRIMARY KEY,
  profesor TEXT NOT NULL,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  dejada INTEGER NOT NULL DEFAULT 0,
  tarea TEXT DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alumnos_fuera_aula (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  profesor TEXT NOT NULL,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  cantidad INTEGER NOT NULL DEFAULT 0 CHECK(cantidad >= 0 AND cantidad <= 10),
  last_exit_at TEXT DEFAULT '',
  last_return_at TEXT DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(profesor, dia, hora)
);

CREATE TABLE IF NOT EXISTS session_overrides (
  id TEXT PRIMARY KEY,
  profesor TEXT NOT NULL,
  dia INTEGER NOT NULL,
  hora INTEGER NOT NULL,
  materia TEXT DEFAULT '',
  grupo TEXT DEFAULT '',
  detalle TEXT DEFAULT '',
  aula TEXT DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_credentials (
  role TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_state (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS grupos_estado (
  grupo TEXT PRIMARY KEY,
  activo INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
